[project]
name = "pdf-filler"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "streamlit",
    "pandas",
    "openpyxl",
    "pypdf",
    "pdfrw",
    "pdf2image",
    "matplotlib",
    "pymupdf",
]
